  //Example instantiation for system 'nios_system'
  nios_system nios_system_inst
    (
      .GPIO_0_to_and_from_the_Expansion_JP1 (GPIO_0_to_and_from_the_Expansion_JP1),
      .GPIO_1_to_and_from_the_Expansion_JP2 (GPIO_1_to_and_from_the_Expansion_JP2),
      .HEX0_from_the_HEX3_HEX0              (HEX0_from_the_HEX3_HEX0),
      .HEX1_from_the_HEX3_HEX0              (HEX1_from_the_HEX3_HEX0),
      .HEX2_from_the_HEX3_HEX0              (HEX2_from_the_HEX3_HEX0),
      .HEX3_from_the_HEX3_HEX0              (HEX3_from_the_HEX3_HEX0),
      .HEX4_from_the_HEX7_HEX4              (HEX4_from_the_HEX7_HEX4),
      .HEX5_from_the_HEX7_HEX4              (HEX5_from_the_HEX7_HEX4),
      .HEX6_from_the_HEX7_HEX4              (HEX6_from_the_HEX7_HEX4),
      .HEX7_from_the_HEX7_HEX4              (HEX7_from_the_HEX7_HEX4),
      .KEY_to_the_Pushbuttons               (KEY_to_the_Pushbuttons),
      .LEDG_from_the_Green_LEDs             (LEDG_from_the_Green_LEDs),
      .LEDR_from_the_Red_LEDs               (LEDR_from_the_Red_LEDs),
      .SRAM_ADDR_from_the_SRAM              (SRAM_ADDR_from_the_SRAM),
      .SRAM_CE_N_from_the_SRAM              (SRAM_CE_N_from_the_SRAM),
      .SRAM_DQ_to_and_from_the_SRAM         (SRAM_DQ_to_and_from_the_SRAM),
      .SRAM_LB_N_from_the_SRAM              (SRAM_LB_N_from_the_SRAM),
      .SRAM_OE_N_from_the_SRAM              (SRAM_OE_N_from_the_SRAM),
      .SRAM_UB_N_from_the_SRAM              (SRAM_UB_N_from_the_SRAM),
      .SRAM_WE_N_from_the_SRAM              (SRAM_WE_N_from_the_SRAM),
      .SW_to_the_Slider_switches            (SW_to_the_Slider_switches),
      .UART_RXD_to_the_Serial_port          (UART_RXD_to_the_Serial_port),
      .UART_TXD_from_the_Serial_port        (UART_TXD_from_the_Serial_port),
      .clk                                  (clk),
      .reset_n                              (reset_n),
      .zs_addr_from_the_SDRAM               (zs_addr_from_the_SDRAM),
      .zs_ba_from_the_SDRAM                 (zs_ba_from_the_SDRAM),
      .zs_cas_n_from_the_SDRAM              (zs_cas_n_from_the_SDRAM),
      .zs_cke_from_the_SDRAM                (zs_cke_from_the_SDRAM),
      .zs_cs_n_from_the_SDRAM               (zs_cs_n_from_the_SDRAM),
      .zs_dq_to_and_from_the_SDRAM          (zs_dq_to_and_from_the_SDRAM),
      .zs_dqm_from_the_SDRAM                (zs_dqm_from_the_SDRAM),
      .zs_ras_n_from_the_SDRAM              (zs_ras_n_from_the_SDRAM),
      .zs_we_n_from_the_SDRAM               (zs_we_n_from_the_SDRAM)
    );

